---
- name: set mysql variables
  set_fact:
    wp_mysql_db: wpmysql
    wp_mysql_user: wpuser
    wp_mysql_password: wppasss
    wp_mysql_host: sedhst

- name: Install mysql client
  apt:
    name: mysql-client
    state: present
